### ISSUE TITLE
MQTT server in Go

### ISSUE THREAD

**Issue by justb4** [gost/server#67] opened 2016-12-23 12:32 UTC
I read: https://github.com/Geodan/gost/wiki/MQTT and the need for an MQTT server in Go. . I've been successfully working with products from InfluxData: https://www.influxdata.com/ like InfluxDB. 

I saw this announcement:
https://www.influxdata.com/mqtt-surgemq-iot-influxdb-internet-of-things. The SurgeMQ is an MQTT Server in Go: https://github.com/influxdata/surgemq, maybe that is an idea for integration in GOST.

**Comment by bertt** [comment] 2016-12-23 18:16
thanks for this tip, we'll consider it. Current solution we have works quite well, except there
were mosquitto crashes sometimes (see https://github.com/Geodan/gost/issues/40), maybe this is fixed in the meantime.

**Comment by tebben** [comment] 2017-01-02 08:13
Yes SurgeMQ looks promising and was already on my radar, with the use of it we can remove the GOST prefix in the publish topics and also support ?$select=property1,property2 as described in Requirement 45. I will look into it when test level 3 passes (filtering)

**Comment by bertt** [comment] 2017-04-04 07:25
I see some warnings on the SurgeMQ site: "development is currently on hold", "considered unstable until further notice"
Are there stable alternatives?

**Comment by bertt** [comment] 2017-09-04 10:05
duplicate of https://github.com/gost/server/issues/136

**Closed by bertt** 2017-09-04 10:05 UTC
